<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Description' => 'Описание',
    'Published at' => 'Опубликовано',
    'Apply to' => 'Подходит для',
    'Category' => 'Категория',
    'Choose' => 'Выбрать',
    'Choose automobile' => 'Выберите автомобиль',
    'Choose automobile...' => 'Выберите автомобиль...',
    'Condition' => 'Состояние',
    'Contacts' => 'Контакты',
    'Mark' => 'Марка',
    'Model' => 'Модель',
    'Modification' => 'Модификация',
    'Part for' => 'Запчасть для',
    'Part name' => 'Название запчасти',
    'Search' => 'Найти',
    'Seller type' => 'Продавец',
    'Serie' => 'Серия',
    'and {n, plural, =0{automobiles} =1{automobile} one{# automobile} few{# few automobiles} many{# automobiles} other{# automobiles}}' => 'и еще {n, plural, =0{автомобилей} =1{автомобиля} one{# автомобиля} few{# few автомобилей} many{# автомобилей} other{# автомобилей}}',
    'private person' => 'частное лицо',
];
