<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Price' => 'Цена',
    'from' => 'от',
    'Address' => 'Адрес',
    'Advert description' => 'Описание',
    'Advert title' => 'Заголовок объявления',
    'Advert was created' => 'Объявление создано',
    'Advert was published' => 'Объявление опубликовано',
    'Append advert' => 'Добавить объявление',
    'Apply to' => 'Подходит для',
    'Automobiles' => 'Автомобили',
    'Begin publication' => 'Опубликовано',
    'Category' => 'Категория',
    'Choose' => 'Выбрать',
    'Choose automobile' => 'Выберите автомобиль',
    'Choose automobile...' => 'Выберите автомобиль...',
    'Choose mark' => 'Выберите марку',
    'Choose model' => 'Выберите модель',
    'Choose modification' => 'Выберите модификацию',
    'Choose one or more automobiles' => 'Выберите один или более автомобилей',
    'Choose serie' => 'Выберите серию',
    'Collapse extended search params' => 'Скрыть расширенные параметры',
    'Complete publication' => 'Завершена публикация',
    'Condition' => 'Состояние',
    'Contact email' => 'E-mail (не публикуется)',
    'Contact face' => 'Контактное лицо',
    'Contact name' => 'Контактное лицо',
    'Contact phone' => 'Контактный телефон',
    'Contacts' => 'Контакты',
    'Description' => 'Описание',
    'E-mail' => 'E-mail',
    'Edit' => 'Редактировать',
    'Edit advert' => 'Редактирование объявления',
    'Extend search params' => 'Расширенный поиск',
    'Images' => 'Изображения',
    'Mark' => 'Марка',
    'Max files is: {n}' => 'Можно загрузить максимум {n} файлов',
    'Model' => 'Модель',
    'Modification' => 'Модификация',
    'My adverts' => 'Мои объявления',
    'Name' => 'Название',
    'Part category' => 'Категория запчасти',
    'Part condition' => 'Состояние запчасти',
    'Part for' => 'Запчасть для',
    'Part name' => 'Название запчасти',
    'Part price' => 'Цена',
    'Phone' => 'Телефон',
    'Place an advert' => 'Разместить объявление',
    'Price from' => 'Цена от',
    'Price to' => 'Цена до',
    'Publish to {date}' => 'Опубликовать до {date}',
    'Published at' => 'Опубликовано',
    'Published to' => 'Опубликовано до',
    'Region' => 'Регион',
    'Related adverts' => 'Похожие объявления',
    'Required field' => 'Поле обязательно для заполнения',
    'Search' => 'Найти',
    'Seller' => 'Продавец',
    'Seller type' => 'Продавец',
    'Serie' => 'Серия',
    'Show other regions' => 'Показывать результаты в других регионах',
    'Stop advert publication' => 'Завершить публикацию',
    'System error.' => 'Системная ошибка.',
    'Trade point' => 'Торговая точка',
    'Unpublished' => 'Неопубликовано',
    'Update advert' => 'Обновить объявление',
    'User id' => 'Пользователь',
    'View' => 'Просмотреть',
    'and {n, plural, =0{automobiles} =1{automobile} one{# automobile} few{# few automobiles} many{# automobiles} other{# automobiles}}' => 'и еще {n, plural, =0{автомобилей} =1{автомобиля} one{# автомобиля} few{# few автомобилей} many{# автомобилей} other{# автомобилей}}',
    'private person' => 'частное лицо',
    'to' => 'до',
];
