<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Phone' => 'Телефон',
    'Address' => 'Адрес',
    'Can\'t send request: system error' => 'Невозможно отправить запрос: системная ошибка',
    'Company name' => 'Название компании',
    'Company type' => 'Тип компании',
    'Create' => 'Создать',
    'Create new trade point' => 'Новая торговая точка',
    'Create trade point' => 'Создать торговую точку',
    'Latitude' => 'Широта',
    'Longitude' => 'Долгота',
    'My trade points' => 'Мои торговые точки',
    'Phone from profile' => 'Использовать телефон из профиля',
    'Search by address' => 'Искать по адресу',
    'Search by latitude' => 'Искать по широте',
    'Search by longitude' => 'Искать по долготе',
    'Update' => 'Обновить',
    'Update trade point' => 'Редактировать торговую точку',
    'Use phone from <a href="{link}">profile</a>' => 'Использовать телефон из <a href="{link}" target="_blank">профиля</a>',
    'Use phone from <a href="{link}">profile</a>: {phone}' => 'Использовать телефон из <a href="{link}" target="_blank">профиля</a>: {phone}',
];
