<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Contacts' => 'Контакты',
    'Account locked' => 'Аккаунт заблокирован',
    'Authorize' => 'Авторизация',
    'Change e-mail' => 'Изменить e-mail',
    'Change e-mail error' => 'Ошибка изменения e-mail',
    'Change password' => 'Изменить пароль',
    'Company data' => 'Данные компании',
    'Company data success updated' => 'Данные компании успешно отредактированы',
    'Company data update error' => 'Ошибка редактирования данных',
    'Company name' => 'Название компании',
    'Company type' => 'Тип компании',
    'Current e-mail' => 'Текущий e-mail',
    'E-mail' => 'E-mail',
    'E-mail has no changes' => 'Нет изменений в e-mail',
    'E-mail success changed' => 'E-mail успешно изменен',
    'Enter' => 'Войти',
    'Error change e-mail' => 'Ошибка изменения e-mail',
    'Exit' => 'Выход',
    'I am a private person' => 'Я - частное лицо',
    'I am a representative a company' => 'Я - представитель компании',
    'Incorrect username or password.' => 'Неверный логин или пароль',
    'Lost password?' => 'Забыли пароль?',
    'My adverts' => 'Мои объявления',
    'Name' => 'Имя',
    'Need activation' => 'Требуется активация',
    'New e-mail' => 'Новый e-mail',
    'New password' => 'Новый пароль',
    'Password' => 'Пароль',
    'Password changes error' => 'Ошибка редактирования пароля',
    'Password confirmation' => 'Подтверждение пароля',
    'Password not equal' => 'Пароли не совпадают',
    'Password success changed' => 'Пароль успешно изменен',
    'Phone' => 'Телефон',
    'Profile' => 'Профиль',
    'Profile success updated' => 'Профиль обновлен',
    'Profile update error' => 'Ошибка редактирования профиля',
    'Register' => 'Зарегистрироваться',
    'Register type' => 'Тип регистрации',
    'Registration' => 'Регистрация',
    'Restore password' => 'Восстановить пароль',
    'Specialization' => 'Специализация',
    'Success registered' => 'Успешная регистрация',
    'This e-mail already exists' => 'Данный e-mail уже занят',
    'This phone already exists' => 'Данный телефон уже занят',
    'Update data' => 'Редактировать',
    'User not found' => 'Аккаунт не найден',
    'Wrong confirmation code' => 'Ошибочный код подтверждения',
    'You enter as:' => 'Вы вошли как:',
    'Your email' => 'E-mail',
    'Your name' => 'Имя',
    'Your phone' => 'Телефон',
];
