<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Change password' => 'Изменить пароль',
    'Lost password?' => 'Забыли пароль?',
    'New password' => 'Новый пароль',
    'Restore password' => 'Восстановить пароль',
    'User not found' => 'Аккаунт не найден',
    'Account locked' => 'Аккаунт заблокирован',
    'Authorize' => 'Авторизация',
    'E-mail' => 'E-mail',
    'Enter' => 'Войти',
    'Exit' => 'Выход',
    'Incorrect username or password.' => 'Неверный логин или пароль',
    'My adverts' => 'Мои объявления',
    'Need activation' => 'Требуется активация',
    'Password' => 'Пароль',
    'Password confirmation' => 'Подтверждение пароля',
    'Password not equal' => 'Пароли не совпадают',
    'Profile' => 'Профиль',
    'Register' => 'Зарегистрироваться',
    'Registration' => 'Регистрация',
    'Success registered' => 'Успешная регистрация',
    'You enter as:' => 'Вы вошли как:',
    'Your email' => 'E-mail',
    'Your name' => 'Имя',
    'Your phone' => 'Телефон',
];
