<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Advert' => 'Объявления',
    'Adverts list' => 'Список объявлений',
    'Advert categories' => 'Категории объявлений',
    'Advert categories list' => 'Список категорий объявлений',
    'Apply' => 'Применить',
    'Automobiles' => 'Автомобили',
    'Create {modelClass}' => 'Создать {modelClass}',
    'Dashboard index page' => 'Dashboard index page',
    'File list' => 'Список файлов',
    'File storage' => 'Файловое хранилище',
    'Full name' => 'Полное имя',
    'Handbook' => 'Справочники',
    'Hello, {username}' => 'Здравствуйте, {username}',
    'Incorrect username or password.' => 'Неверный логин или пароль.',
    'Last login' => 'Последняя авторизация',
    'Login' => 'Авторизация',
    'Logout' => 'Выйти',
    'Password' => 'Пароль',
    'Remember me' => 'Запомнить меня',
    'Reset' => 'Сбросить',
    'Roles' => 'Роли',
    'Roles list' => 'Список ролей',
    'Save' => 'Сохранить',
    'Search' => 'Поиск',
    'Sign me in' => 'Войти',
    'Toggle navigation' => 'Переключить',
    'Update {modelClass}' => 'Редактировать {modelClass}',
    'Users' => 'Пользователи',
    'Users list' => 'Список пользователей',
];
