<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Last adverts' => 'Последние объвления',
    'Parts for automobiles' => 'Запчасти для автомобилей',
    'Can\'t create advert to this e-mail. <a href="{url}">Details...</a>' => 'Для публикации объявления на этот e-mail необходимо зарегистрироваться. <a href="{url}">Подробнее</a>',
    'Can\'t create advert to this phone. <a href="{url}">Details...</a>' => 'Для публикации объявления на этот телефон необходимо зарегистрироваться. <a href="{url}">Подробнее</a>',
    'Created' => 'Создано',
    'Drag & drop files here for upload' => 'Для загрузки перетащите файлы в это окно',
    'Edited' => 'Отредактировано',
    'No' => 'Нет',
    'Phone already exists' => 'Телефон уже используется',
    'Submit' => 'Отправить',
    'Wrong phone format' => 'Неверный формат телефона',
    'Yes' => 'Да',
    'today' => 'сегодня',
    'tomorrow' => 'завтра',
    'yesterday' => 'вчера',
];
