<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Advert list' => 'Список объявлений',
    'Auto' => 'Автомобили',
    'Common settings' => 'Общие настройки',
    'Error update a advert' => 'Ошибка редактирования объявления',
    'Success update advert' => 'Успешно отредактировано объявление',
    'Error create a advert' => 'Ошибка создания объявления',
    'Error create a category' => 'Ошибка создания категории',
    'Error update a category' => 'Ошибка обновления категории',
    'Success create advert' => 'Успешно создано объявление',
    'Success create category' => 'Успешно создана категория',
    'Success update category' => 'Успешно обновлена категория',
    'of advert' => 'объявление',
    'of category' => 'категорию',
];
