<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Error create a partner' => 'Ошибка создания партнера',
    'Error create a trade point' => 'Ошибка создания торговой точки',
    'Error update a partner' => 'Ошибка обновления партнера',
    'Error update a trade point' => 'Ошибка обновления торговой точки',
    'Partner delete error' => 'Ошибка удаления партенра',
    'Partner success deleted' => 'Партнер успешно удален',
    'Partners list' => 'Список партнеров',
    'Success create partner' => 'Партнер успешно создан',
    'Success create trade point' => 'Торговая точка успешно создана',
    'Success update partner' => 'Партнер успешно обновлен',
    'Success update trade point' => 'Торговая точка успешно обновлена',
    'Trade point delete error' => 'Ошибка удаления торговой точки',
    'Trade point success deleted' => 'Торговая точка успешно удалена',
    'Trade points list' => 'Список торговых точек',
    'of partner' => 'партнера',
    'of trade point' => 'торговую точку',
];
