<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'of role' => 'роль',
    'of user' => 'пользователя',
    'Common settings' => 'Общие настройки',
    'Description' => 'Описание',
    'Error create a user' => 'Ошибка создания пользователя',
    'Error creating a role' => 'Ошибка создания роли',
    'Error update a user' => 'Ошибка обновления пользователя',
    'Error update role' => 'Ошибка обновления роли',
    'Name' => 'Название',
    'Permissions' => 'Права',
    'Role already exists' => 'Роль уже существует',
    'Role list' => 'Список ролей',
    'Success create role' => 'Успешно создана роль',
    'Success create user' => 'Успешно создан пользователь',
    'Success update role' => 'Успешно обновлена роль',
    'Success update user' => 'Успешно обновлен пользователь',
    'User list' => 'Список пользователей',
    'User roles' => 'Права пользователя',
];
